# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-28 02:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ZipCode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('city', models.CharField(max_length=255)),
                ('state', models.CharField(max_length=2)),
                ('address', models.CharField(max_length=255)),
                ('zip_code', models.CharField(max_length=8)),
                ('neighborhood', models.CharField(max_length=255)),
            ],
            options={
                'ordering': ['-created_at'],
                'db_table': 'zip_codes',
            },
        ),
    ]
