# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-29 02:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zipcodes', '0004_auto_20160129_0226'),
    ]

    operations = [
        migrations.AlterField(
            model_name='zipcode',
            name='neighborhood',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
